# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  errors:
    always_put_control_body_on_new_line: ignore
    invalid_annotation_target: ignore
    avoid_positional_boolean_parameters: ignore
  exclude:
    - "**/firebase_options.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
