name: test_interval
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  freezed_annotation:
  go_router: ^3.0.1
  hooks_riverpod: ^1.0.3
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.12

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  hive_generator: ^1.1.1
  json_serializable:
  pedantic_mono: any

flutter:
  uses-material-design: true
